name: Qcirc
channels:
  - conda-forge
  - defaults
dependencies:
  - argh=0.26.2
  - blas=1.0
  - certifi=2018.11.29
  - cycler=0.10.0
  - freetype=2.9.1
  - kiwisolver=1.0.1
  - matplotlib=2.2.3
  - mkl=2018.0.3
  - mkl_fft=1.0.5
  - mkl_random=1.0.1
  - numpy=1.15.0
  - numpy-base=1.15.0
  - pandas=0.23.4
  - pathtools=0.1.2
  - patsy=0.5.0
  - psutil=5.5.0
  - pyparsing=2.2.0
  - python=3.6.8
  - python-dateutil=2.7.3
  - pytz=2018.5
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.0.0
  - six=1.11.0
  - sqlalchemy=1.2.10
  - statsmodels=0.9.0
  - tornado=5.1
  - wheel=0.31.1
  - pip
  - pip:
    - argparse==1.4.0
    - aspy-yaml==1.1.1
    - atomicwrites==1.2.1
    - attrs==18.1.0
    - cached-property==1.4.3
    - cfgv==1.1.0
    - future==0.16.0
    - identify==1.1.4
    - mock==2.0.0
    - more-itertools==4.3.0
    - nodeenv==1.3.2
    - pbr==4.2.0
    - pluggy==0.7.1
    - pre-commit==1.10.5
    - py==1.6.0
    - pyswarms==0.3.1
    - pytest==3.6.4
    - pyyaml==3.13
    - toml==0.9.4
    - virtualenv==16.0.0
    - watchdog==2.1.6
